services:
  wajik-anime-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wajik-anime-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
